version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

    env_file:
      - ./.env

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dummy123
      - POSTGRES_DB=social-fastapi
    volumes:
      - socialposts-db:/var/lib/postgresql/data

volumes:
  socialposts-db: