version: "3"
services:
  api:
    build: .
    ports: 
      - 8000:8000
    env_file:
      - ./.env

  postgres:
    image:
    environment:
      - POSTGRES_PASSWORD=dummy123
      - POSTGRES_DB=social-fastapi
    volumes:
      - socialposts-db:/var/lib/postgresql/data

volumes:
  socialposts-db: